import os
import io
import re
import streamlit as st
import google.generativeai as genai
from dotenv import load_dotenv

from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors

from utils.pdf_reader import extract_text_from_pdf
from agents.summary_agent import run_summary_agent
from agents.methodology_agent import run_methodology_agent
from agents.evaluation_agent import run_evaluation_agent
from agents.research_mentor_agent import run_research_mentor_agent
from agents.safety_agent import run_safety_agent


def generate_final_report(summary, methodology, evaluation, future_work, safety_review):
    return f"""
# ResearchMate AI Final Research Report

## 1. Summary Agent Output
{summary}

---

## 2. Methodology Agent Output
{methodology}

---

## 3. Evaluation Agent Output
{evaluation}

---

## 4. Research Mentor Agent Output
{future_work}

---

## 5. Safety Review Agent Output
{safety_review}

---

## Human-in-the-Loop Notice

This report was generated by an AI-powered multi-agent system. The output should be reviewed by a human researcher before academic, clinical, or professional use.

---

Generated by ResearchMate AI.
"""


def clean_markdown(text):
    text = text.replace("&", "&amp;")
    text = re.sub(r"\*\*(.*?)\*\*", r"<b>\1</b>", text)
    return text


def create_pdf_report(report_text):
    buffer = io.BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=50,
        leftMargin=50,
        topMargin=50,
        bottomMargin=50,
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "CustomTitle",
        parent=styles["Title"],
        fontSize=24,
        leading=30,
        spaceAfter=22,
        textColor=colors.HexColor("#263B8E"),
    )

    heading_style = ParagraphStyle(
        "CustomHeading",
        parent=styles["Heading2"],
        fontSize=15,
        leading=19,
        spaceBefore=16,
        spaceAfter=8,
        textColor=colors.HexColor("#263B8E"),
    )

    body_style = ParagraphStyle(
        "CustomBody",
        parent=styles["BodyText"],
        fontSize=10,
        leading=14,
        spaceAfter=6,
    )

    bullet_style = ParagraphStyle(
        "CustomBullet",
        parent=body_style,
        leftIndent=18,
        bulletIndent=8,
    )

    story = []
    story.append(Paragraph("ResearchMate AI", title_style))
    story.append(Paragraph("Final Research Report", heading_style))
    story.append(
        Paragraph(
            "Generated by a multi-agent AI research assistant. This report should be reviewed by a human researcher before academic, clinical, or professional use.",
            body_style,
        )
    )
    story.append(PageBreak())

    for line in report_text.split("\n"):
        line = line.strip()

        if not line:
            story.append(Spacer(1, 6))
        elif line.startswith("# "):
            story.append(Paragraph(clean_markdown(line.replace("# ", "")), title_style))
        elif line.startswith("## "):
            story.append(Paragraph(clean_markdown(line.replace("## ", "")), heading_style))
        elif line.startswith("### "):
            story.append(Paragraph(clean_markdown(line.replace("### ", "")), heading_style))
        elif line.startswith("* ") or line.startswith("- "):
            story.append(Paragraph(clean_markdown(line[2:]), bullet_style, bulletText="•"))
        elif line.startswith("---"):
            story.append(Spacer(1, 12))
        else:
            story.append(Paragraph(clean_markdown(line), body_style))

    doc.build(story)
    buffer.seek(0)
    return buffer


load_dotenv()
api_key = os.getenv("GEMINI_API_KEY")

if api_key:
    genai.configure(api_key=api_key)

st.set_page_config(
    page_title="ResearchMate AI",
    page_icon="📚",
    layout="wide",
)

st.markdown(
    """
<style>
[data-testid="stAppViewContainer"] {
    background: linear-gradient(135deg, #f8fbff 0%, #ffffff 48%, #fbf7ff 100%);
}

[data-testid="stHeader"] {
    background: rgba(255,255,255,0);
}

.block-container {
    padding-top: 2rem;
    padding-bottom: 3rem;
    max-width: 1320px;
}

/* HERO */
.hero {
    text-align: center;
    padding: 46px 50px;
    border-radius: 32px;
    background: radial-gradient(circle at top left, #eaf2ff 0%, #ffffff 45%, #f6edff 100%);
    border: 1px solid #e4eaff;
    box-shadow: 0px 18px 45px rgba(74, 85, 162, 0.10);
    margin-bottom: 28px;
}

.hero-title {
    font-size: 60px;
    font-weight: 950;
    color: #121936;
    margin-bottom: 8px;
    letter-spacing: -1px;
}

.hero-subtitle {
    font-size: 25px;
    font-weight: 750;
    color: #273067;
    margin-bottom: 8px;
}

.hero-highlight {
    color: #5B3DF5;
}

.hero-desc {
    font-size: 17px;
    color: #42496a;
    line-height: 1.6;
    max-width: 850px;
    margin: 18px auto 0 auto;
}

.badge {
    display: inline-block;
    padding: 10px 18px;
    border-radius: 999px;
    background: linear-gradient(90deg, #efe7ff, #eaf2ff);
    color: #4c25d9;
    font-weight: 800;
    font-size: 14px;
    margin-top: 16px;
    border: 1px solid #dacbff;
}

.cta-text {
    margin-top: 20px;
    font-size: 16px;
    font-weight: 800;
    color: #263B8E;
}

.section-title {
    font-size: 30px;
    font-weight: 900;
    color: #19203d;
    margin-top: 30px;
    margin-bottom: 18px;
}

/* STATS */
.mini-stat {
    text-align: center;
    padding: 18px 16px;
    border-radius: 18px;
    background: rgba(255,255,255,0.85);
    border: 1px solid #e0e7ff;
    box-shadow: 0 10px 24px rgba(74, 85, 162, 0.07);
}

.mini-stat-num {
    font-size: 26px;
    font-weight: 950;
    color: #4f46e5;
}

.mini-stat-label {
    font-size: 13px;
    color: #4b5563;
    font-weight: 700;
}

/* HOW IT WORKS */
.step-card {
    min-height: 220px;
    padding: 24px 22px 32px 22px;
    border-radius: 22px;
    background: linear-gradient(160deg, #ffffff 0%, #f6f9ff 100%);
    border: 1.5px solid #d8e9ff;
    box-shadow: 0 12px 28px rgba(37,99,235,0.08);
    display: flex;
    flex-direction: column;
    justify-content: flex-start;
    transition: all 0.25s ease;
}

.step-card:hover {
    transform: translateY(-5px);
    box-shadow: 0 18px 35px rgba(37, 99, 235, 0.13);
}

.step-icon {
    font-size: 34px;
    line-height: 1;
    margin-bottom: 26px;
}

.step-title {
    font-size: 17px;
    font-weight: 900;
    color: #0f5fcf;
    line-height: 1.25;
    margin-bottom: 10px;
}

.step-text {
    font-size: 13.5px;
    color: #3d4560;
    line-height: 1.45;
}

/* AGENT CARDS */
.agent-card {
    height: 390px;
    padding: 28px 24px 24px 24px;
    border-radius: 22px;
    border: 1px solid;
    box-shadow: 0 14px 30px rgba(31, 41, 55, 0.07);
    transition: all 0.25s ease;
    display: flex;
    flex-direction: column;
    position: relative;
}

.agent-card:hover {
    transform: translateY(-7px) scale(1.01);
    box-shadow: 0 22px 45px rgba(31, 41, 55, 0.13);
}

.agent-num {
    position: absolute;
    top: 18px;
    right: 18px;
    font-size: 13px;
    font-weight: 900;
    padding: 6px 12px;
    border-radius: 12px;
}

.agent-icon {
    font-size: 48px;
    margin-bottom: 26px;
    margin-top: 6px;
}

.agent-title {
    font-size: 22px;
    font-weight: 900;
    margin-bottom: 18px;
    line-height: 1.25;
}

.agent-text {
    font-size: 15px;
    line-height: 1.55;
    color: #34405f;
    flex-grow: 1;
}

.skill-pill {
    display: inline-block;
    padding: 8px 14px;
    border-radius: 999px;
    font-size: 13px;
    font-weight: 850;
    width: fit-content;
    margin-top: auto;
}

.blue-card {
    background: linear-gradient(160deg, #eef6ff 0%, #ffffff 58%, #e9f3ff 100%);
    border-color: #add3ff;
}
.blue-card .agent-title { color: #075fc7; }
.blue-card .agent-num, .blue-card .skill-pill { background: #d4eaff; color: #075fc7; }

.purple-card {
    background: linear-gradient(160deg, #f5eeff 0%, #ffffff 58%, #f1e8ff 100%);
    border-color: #d2bcff;
}
.purple-card .agent-title { color: #6733d1; }
.purple-card .agent-num, .purple-card .skill-pill { background: #e8d8ff; color: #6733d1; }

.green-card {
    background: linear-gradient(160deg, #effcf5 0%, #ffffff 58%, #e7f9ef 100%);
    border-color: #ade7c1;
}
.green-card .agent-title { color: #0f8546; }
.green-card .agent-num, .green-card .skill-pill { background: #d2f4de; color: #0f8546; }

.orange-card {
    background: linear-gradient(160deg, #fff5e8 0%, #ffffff 58%, #fff0dc 100%);
    border-color: #ffc88e;
}
.orange-card .agent-title { color: #d45a00; }
.orange-card .agent-num, .orange-card .skill-pill { background: #ffdfb8; color: #d45a00; }

.red-card {
    background: linear-gradient(160deg, #fff0f0 0%, #ffffff 58%, #ffe8e8 100%);
    border-color: #ffb9b9;
}
.red-card .agent-title { color: #d6272f; }
.red-card .agent-num, .red-card .skill-pill { background: #ffd1d1; color: #d6272f; }

/* WORKFLOW */
div[data-testid="stExpander"] {
    border-radius: 16px !important;
    overflow: hidden;
    margin: 24px 0 !important;
    border: 1px solid #e5e7eb !important;
    box-shadow: 0 4px 6px rgba(0, 0, 0, 0.02);
}

div[data-testid="stExpander"] details summary {
    min-height: 56px !important;
    padding: 16px 24px !important;
    font-size: 16px !important;
    font-weight: 700 !important;
    background: linear-gradient(135deg, #f8f9ff, #ffffff);
}

div[data-testid="stExpander"] div[role="region"] {
    padding: 24px !important;
}

.workflow-wrap {
    padding: 16px 24px !important;
    margin: 16px 0 28px 0 !important;
    border-radius: 16px;
    background: #ffffff;
    border: 1px solid #e2e8ff;
    box-shadow: 0 8px 24px rgba(74, 85, 162, 0.08);
    overflow-x: auto;
}

.workflow-row {
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 18px;
    min-width: 900px;
    padding: 12px 0 16px 0;
}

.workflow-node {
    min-width: 140px;
    text-align: center;
    padding: 14px 20px;
    border-radius: 14px;
    background: linear-gradient(135deg, #ffffff, #f8faff);
    border: 1px solid #dfe5ff;
    font-size: 15px;
    font-weight: 700;
    color: #26315f;
    box-shadow: 0 4px 12px rgba(74, 85, 162, 0.06);
    white-space: nowrap;
    transition: transform 0.2s ease, box-shadow 0.2s ease;
}

.workflow-node:hover {
    transform: translateY(-2px);
    box-shadow: 0 6px 16px rgba(74, 85, 162, 0.12);
}

.workflow-arrow {
    font-size: 20px;
    color: #4f46e5;
    font-weight: 900;
}

/* UPLOAD */
/* UPLOAD */
.upload-helper {
    color: #64748b;
    font-size: 15px;
    margin-bottom: 14px;
    line-height: 1.6;
    max-width: 720px;
}

.upload-note {
    margin-top: 12px;
    padding: 14px 16px;
    border-radius: 16px;
    background: linear-gradient(135deg, #f8fbff, #ffffff);
    border: 1px solid #dbe8ff;
    color: #334155;
    font-size: 14px;
    line-height: 1.7;
}

/* OUTPUT */
.output-box {
    padding: 22px;
    border-radius: 20px;
    background: linear-gradient(135deg, #f4f8ff, #ffffff);
    border: 1px solid #dce6ff;
    margin-top: 18px;
    margin-bottom: 18px;
}

.check-card {
    padding: 20px;
    border-radius: 22px;
    background: linear-gradient(135deg, #f4fff8, #ffffff);
    border: 1px solid #d4f3df;
    box-shadow: 0 12px 24px rgba(22, 163, 74, 0.06);
    line-height: 1.9;
    color: #253044;
}

.footer-warning {
    padding: 15px 18px;
    border-radius: 14px;
    background: #fff8e8;
    border-left: 5px solid #f4b740;
    color: #5f4210;
    font-weight: 650;
}

/* FOOTER */
.footer {
    text-align: center;
    padding: 22px 20px;
    margin: 40px auto 0 auto;
    max-width: 600px;
    border-radius: 24px;
    background: linear-gradient(135deg, #fafbff 0%, #ffffff 100%);
    transition: all .25s ease;
    border: 1px solid #e7ebff;
    box-shadow: 0 10px 25px rgba(74,85,162,0.05);
}

.footer:hover {
    transform: translateY(-2px);
    box-shadow: 0 14px 35px rgba(74,85,162,.08);
}

.footer-title {
    font-size: 22px;
    font-weight: 900;
    color: #18214a;
    margin-bottom: 8px;
}

.footer-subtitle {
    font-size: 15px;
    color: #5a647f;
    margin-bottom: 18px;
}

.footer-divider {
    width: 120px;
    height: 4px;
    background: linear-gradient(90deg, #4f46e5, #8b5cf6);
    border-radius: 999px;
    margin: 18px auto 24px auto;
}

.footer-tech {
    font-size: 15px;
    line-height: 1.7;
    max-width: 700px;
    margin: 0 auto;
}

.footer-credit {
    margin-top: 14px;
    font-size: 17px;
    color: #4b5563;
}

.footer-credit strong {
    color: #18214a;
}
</style>
""",
    unsafe_allow_html=True,
)

st.markdown(
    """
<div class="hero">
    <div class="hero-title">📚 ResearchMate AI ✨</div>
    <div class="hero-subtitle">Multi-Agent Research Paper Assistant<br>
    <span class="hero-highlight">powered by Gemini and Agent Skills</span></div>
    <div class="badge">🏆 Capstone Project — Kaggle AI Agents Intensive Vibe Coding Course 2026</div>
    <div class="hero-desc">
        Transform research papers into structured insights using specialized AI agents for summarization,
        methodology analysis, evaluation, research mentoring, safety review, and final report generation.
    </div>
    <div class="cta-text">🚀 Upload a PDF below to start the multi-agent research analysis</div>
</div>
""",
    unsafe_allow_html=True,
)

s1, s2, s3, s4 = st.columns(4)
stats = [
    ("5", "Specialized Agents"),
    ("6", "Report Sections"),
    ("PDF + MD", "Export Formats"),
    ("Safety", "Human Review Layer"),
]

for col, (num, label) in zip([s1, s2, s3, s4], stats):
    with col:
        st.markdown(
            f"""
            <div class="mini-stat">
                <div class="mini-stat-num">{num}</div>
                <div class="mini-stat-label">{label}</div>
            </div>
            """,
            unsafe_allow_html=True,
        )

st.markdown('<div class="section-title">⚙️ How ResearchMate AI Works</div>', unsafe_allow_html=True)

w1, w2, w3, w4, w5 = st.columns(5)

workflow_cards = [
    ("1. Upload PDF", "Upload your academic research paper.", "⬆️"),
    ("2. Extract Text", "Read and clean PDF content.", "📄"),
    ("3. Multi-Agent Analysis", "Five specialized agents analyze the paper.", "🤖"),
    ("4. Consolidate", "Merge outputs into one final report.", "🧩"),
    ("5. Export Report", "Download as PDF or Markdown.", "⬇️"),
]

for col, (title, text, icon) in zip([w1, w2, w3, w4, w5], workflow_cards):
    with col:
        st.markdown(
            f"""
            <div class="step-card">
                <div class="step-icon">{icon}</div>
                <div>
                    <div class="step-title">{title}</div>
                    <div class="step-text">{text}</div>
                </div>
            </div>
            """,
            unsafe_allow_html=True,
        )

st.markdown('<div class="section-title">🤖 Agent System Overview</div>', unsafe_allow_html=True)

c1, c2, c3, c4, c5 = st.columns(5)

agent_cards = [
    (c1, "blue-card", "01", "📄", "Summary Agent",
     "Generates beginner-friendly summaries of the research problem, objectives, findings, and contribution.", "Summarization"),
    (c2, "purple-card", "02", "🔬", "Methodology Agent",
     "Extracts datasets, preprocessing pipelines, model designs, experimental setup, and research methods.", "Methodology"),
    (c3, "green-card", "03", "📊", "Evaluation Agent",
     "Reviews results, metrics, comparisons, limitations, and evaluation strategies.", "Evaluation"),
    (c4, "orange-card", "04", "🎓", "Mentor Agent",
     "Suggests research gaps, future work, experiment ideas, and possible improvements.", "Mentorship"),
    (c5, "red-card", "05", "🛡️", "Safety Agent",
     "Checks unsupported claims, unsafe conclusions, speculative language, and missing disclaimers.", "Safety Review"),
]

for col, color, num, icon, title, text, pill in agent_cards:
    with col:
        st.markdown(
            f"""
            <div class="agent-card {color}">
                <span class="agent-num">{num}</span>
                <div class="agent-icon">{icon}</div>
                <div class="agent-title">{title}</div>
                <div class="agent-text">{text}</div>
                <span class="skill-pill">{pill}</span>
            </div>
            """,
            unsafe_allow_html=True,
        )

with st.expander("🧠 Multi-Agent Workflow Architecture", expanded=True):
    st.markdown(
        """
        <div class="workflow-wrap">
            <div class="workflow-row">
                <div class="workflow-node">👤 User</div>
                <div class="workflow-arrow">→</div>
                <div class="workflow-node">📤 PDF Upload</div>
                <div class="workflow-arrow">→</div>
                <div class="workflow-node">📄 PDF Extraction</div>
                <div class="workflow-arrow">→</div>
                <div class="workflow-node">🤖 Coordinator</div>
                <div class="workflow-arrow">→</div>
                <div class="workflow-node">🧠 5 Agents</div>
                <div class="workflow-arrow">→</div>
                <div class="workflow-node">📑 Final Report</div>
            </div>
        </div>
        """,
        unsafe_allow_html=True,
    )

st.divider()

left, right = st.columns([2.2, 1])

with left:
    st.markdown(
        '<div class="section-title">📤 Upload Research Paper</div>',
        unsafe_allow_html=True
    )

    st.markdown(
        """
        <div class="upload-helper">
            Upload one academic PDF and ResearchMate AI will generate a structured
            multi-agent research analysis report.
        </div>
        """,
        unsafe_allow_html=True,
    )

    uploaded_file = st.file_uploader(
        "Upload a research paper PDF",
        type=["pdf"],
        label_visibility="collapsed",
    )

    st.markdown(
        """
        <div class="upload-note">
            <b>Supported:</b> Research articles, review papers, thesis chapters, and conference papers.<br>
            <b>Output:</b> Summary, methodology, evaluation, research suggestions, safety review, and final report.
        </div>
        """,
        unsafe_allow_html=True,
    )

with right:
    st.markdown(
        '<div class="section-title">✅ What You Will Get</div>',
        unsafe_allow_html=True
    )

    st.markdown(
        """
        <div class="check-card">
        ✅ Comprehensive paper summary<br>
        ✅ Methodology breakdown<br>
        ✅ Results and evaluation analysis<br>
        ✅ Future research recommendations<br>
        ✅ Safety and reliability review<br>
        ✅ Downloadable final report
        </div>
        """,
        unsafe_allow_html=True,
    )

if not api_key:
    st.error("Gemini API key not found. Please add GEMINI_API_KEY to your .env file.")

if uploaded_file is not None and api_key:
    with st.spinner("Extracting text from PDF..."):
        paper_text = extract_text_from_pdf(uploaded_file)

    if len(paper_text.strip()) == 0:
        st.error("No readable text found in this PDF.")
    else:
        st.success("PDF text extracted successfully.")

        word_count = len(paper_text.split())
        char_count = len(paper_text)

        m1, m2, m3, m4 = st.columns(4)
        m1.metric("Words Extracted", f"{word_count:,}")
        m2.metric("Characters", f"{char_count:,}")
        m3.metric("Specialized Agents", 5)
        m4.metric("Report Sections", 6)

        with st.expander("Preview extracted text"):
            st.write(paper_text[:3000])

        if st.button("🚀 Run Multi-Agent Analysis", use_container_width=True):
            progress = st.progress(0)
            status = st.status("Running Multi-Agent Analysis...", expanded=True)

            try:
                with st.spinner("Summary Agent is analyzing the paper..."):
                    summary = run_summary_agent(paper_text)
                    progress.progress(20)
                    status.write("✅ Summary Agent completed")

                with st.spinner("Methodology Agent is extracting methodology..."):
                    methodology = run_methodology_agent(paper_text)
                    progress.progress(40)
                    status.write("✅ Methodology Agent completed")

                with st.spinner("Evaluation Agent is analyzing results..."):
                    evaluation = run_evaluation_agent(paper_text)
                    progress.progress(60)
                    status.write("✅ Evaluation Agent completed")

                with st.spinner("Research Mentor Agent is generating future work ideas..."):
                    future_work = run_research_mentor_agent(paper_text)
                    progress.progress(80)
                    status.write("✅ Research Mentor Agent completed")

                with st.spinner("Safety Review Agent is checking the outputs..."):
                    safety_review = run_safety_agent(summary, methodology, evaluation, future_work)
                    progress.progress(100)
                    status.write("✅ Safety Review Agent completed")

                final_report = generate_final_report(
                    summary,
                    methodology,
                    evaluation,
                    future_work,
                    safety_review,
                )

                pdf_report = create_pdf_report(final_report)
                status.write("✅ Final Research Report generated")
                status.update(label="Multi-Agent Analysis Complete", state="complete", expanded=False)

                st.success("Multi-agent analysis completed successfully.")
                st.divider()

                st.markdown(
                    '<div class="section-title">🧠 Multi-Agent Analysis Results</div>',
                    unsafe_allow_html=True,
                )

                tab1, tab2, tab3, tab4, tab5, tab6 = st.tabs(
                    [
                        "📄 Summary",
                        "🔬 Methodology",
                        "📊 Evaluation",
                        "🎓 Research Mentor",
                        "🛡️ Safety Review",
                        "📑 Final Report",
                    ]
                )

                with tab1:
                    st.subheader("📄 Summary Agent Output")
                    st.markdown(summary)

                with tab2:
                    st.subheader("🔬 Methodology Agent Output")
                    st.markdown(methodology)

                with tab3:
                    st.subheader("📊 Evaluation Agent Output")
                    st.markdown(evaluation)

                with tab4:
                    st.subheader("🎓 Research Mentor Agent Output")
                    st.markdown(future_work)

                with tab5:
                    st.subheader("🛡️ Safety Review Agent Output")
                    st.markdown(safety_review)

                with tab6:
                    st.subheader("📑 Final Research Report")
                    st.markdown(final_report)

                    st.markdown(
                        """
                        <div class="output-box">
                        <h4>📦 Export Final Report</h4>
                        <p>Download the consolidated multi-agent research analysis as Markdown or PDF.</p>
                        </div>
                        """,
                        unsafe_allow_html=True,
                    )

                    d1, d2 = st.columns(2)

                    with d1:
                        st.download_button(
                            label="⬇️ Download Markdown Report",
                            data=final_report,
                            file_name="researchmate_final_report.md",
                            mime="text/markdown",
                            use_container_width=True,
                        )

                    with d2:
                        st.download_button(
                            label="⬇️ Download PDF Report",
                            data=pdf_report,
                            file_name="ResearchMate_Final_Report.pdf",
                            mime="application/pdf",
                            use_container_width=True,
                        )

                st.write("")
                st.markdown(
                    """
                    <div class="footer-warning">
                    ⚠️ Human-in-the-loop reminder: AI-generated research analysis should be reviewed by a human researcher before academic, clinical, or professional decisions.
                    </div>
                    """,
                    unsafe_allow_html=True,
                )

            except Exception as e:
                status.update(label="Analysis stopped", state="error", expanded=True)
                st.error("The analysis could not be completed. This may happen because of API quota limits or temporary Gemini API issues.")
                st.exception(e)

else:
    st.info("Please upload a PDF paper to begin.")

st.markdown(
    """
<div class="footer">
    <div class="footer-title">📚 ResearchMate AI</div>
    <div class="footer-subtitle">Multi-Agent Research Paper Assistant</div>
    <div class="footer-divider"></div>
    <div class="footer-tech">
        Built with Streamlit • Gemini API • Agent Skills • Human-in-the-Loop Safety Review
    </div>
    <div class="footer-credit">
        Created with ❤️ by <strong>Rinvi Jaman Riti</strong>
    </div>
</div>
    """,
    unsafe_allow_html=True,
)