def generate_final_report(
    paper_name,
    summary,
    methodology,
    evaluation,
    mentor,
    safety
):
    report = f"""
# 📚 ResearchMate AI Analysis Report

**Paper:** {paper_name}

---

## Executive Summary
{summary}

---

## Methodology Analysis
{methodology}

---

## Evaluation Analysis
{evaluation}

---

## Research Mentor Recommendations
{mentor}

---

## Safety Review
{safety}

---

## Conclusion

This report consolidates insights from five specialized AI agents:
Summary, Methodology, Evaluation, Research Mentor, and Safety Review.

The combined analysis is intended to help researchers understand,
evaluate, and extend the uploaded paper more efficiently.

---

## Disclaimer

This report was generated by an AI-powered multi-agent system.
The output should be reviewed by a human researcher before academic,
clinical, or professional use.

---

Generated by ResearchMate AI Multi-Agent System
"""

    return report